services:
  dashboard-transaksi-frontend:
    # build: .
    image: ghcr.io/akatgelar/dashboard-transaksi-frontend:latest
    container_name: 'dashboard-transaksi-frontend'  
    ports:
      - "2061:3000"
    restart: always
